<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Join us now</name>
   <tag></tag>
   <elementGuidId>ad15905c-7456-4e47-91f1-c4876477ff57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Join us now&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8545361b-9885-4952-bf77-a9a17efe1180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://forum.katalon.com/latest</value>
      <webElementGuid>fb795483-766b-4bd8-bc1e-a39d1bea7f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Join us now</value>
      <webElementGuid>5dc86b24-fc67-4fde-a3e8-2a5a15ae1026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>1812337a-9f0c-4877-b3a7-8b4bcf37d758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Join us now</value>
      <webElementGuid>1db21e0d-9a1b-41cc-a3d4-b8e87baf270a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;CommunityHub_container__OZzzN&quot;]/section[@class=&quot;HeroSection_heroSection__Vn9C1&quot;]/div[@class=&quot;HeroSection_hero_btn__dd2HZ&quot;]/a[1]</value>
      <webElementGuid>89e6acd8-40c8-43a9-987f-6a9e02a31e7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/div[4]/a</value>
      <webElementGuid>9f8eb01d-9f8f-4ad5-9cf9-709a385fe7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Join us now')]</value>
      <webElementGuid>a613d7bd-f10d-4440-872e-f99f932fe08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://forum.katalon.com/latest')]</value>
      <webElementGuid>ee78a2b3-c85f-4c3a-8fcd-485c13cb8db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[4]/a</value>
      <webElementGuid>1676c726-7e92-47cc-b412-51458bee0870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://forum.katalon.com/latest' and @title = 'Join us now' and (text() = 'Join us now' or . = 'Join us now')]</value>
      <webElementGuid>d65eb6e2-7991-4d12-9147-13fdba28f1ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
