<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>verifyLoginSuite_UsingKeyword_Datadriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e18a1cd1-c317-42a6-bec8-a416cc8d0643</testSuiteGuid>
   <testCaseLink>
      <guid>1505fdb5-95ee-4636-9541-0b6e6d15f31c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Page/Verify login using keyword</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cad6969e-567d-48c3-ba72-607f436be3ef</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/dataLogin_excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>cad6969e-567d-48c3-ba72-607f436be3ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b65d7106-c8ba-417c-82cc-60d81121d01d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cad6969e-567d-48c3-ba72-607f436be3ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pwd</value>
         <variableId>48d8301d-dee2-4e62-8b53-2ef33b166cdf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
